core/main/default/objects/CalloutTracker__e/CalloutTracker__e.object-meta.xml
<CustomObject>
    <description>Track callout activity</description>
    <label>Callout Tracker</label>
    <pluralLabel>Callouts Tracker</pluralLabel>
</CustomObject>

core/main/default/objects/CalloutTracker__e/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <description>Endpoint URL</description>
    <label>Endpoint</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

core/main/default/objects/CalloutTracker__e/fields/EndTime__c.field-meta.xml
<CustomField>
    <fullName>EndTime__c</fullName>
    <description>Request End Time</description>
    <label>End Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

core/main/default/objects/CalloutTracker__e/fields/Headers__c.field-meta.xml
<CustomField>
    <fullName>Headers__c</fullName>
    <description>Header of the request</description>
    <label>Headers</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

core/main/default/objects/CalloutTracker__e/fields/HttpMethod__c.field-meta.xml
<CustomField>
    <fullName>HttpMethod__c</fullName>
    <description>GET, POST, PUT, PATCH, DELETE</description>
    <label>Http Method</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

core/main/default/objects/CalloutTracker__e/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Extra message from the request and response</description>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

core/main/default/objects/CalloutTracker__e/fields/QueryParameters__c.field-meta.xml
<CustomField>
    <fullName>QueryParameters__c</fullName>
    <description>Parameters used in Query URL</description>
    <label>Query Parameters</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

core/main/default/objects/CalloutTracker__e/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <description>Name of the resource that was called</description>
    <label>Resource</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

core/main/default/objects/CalloutTracker__e/fields/ServiceId__c.field-meta.xml
<CustomField>
    <fullName>ServiceId__c</fullName>
    <description>Id of the service that was called</description>
    <label>Service Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

core/main/default/objects/CalloutTracker__e/fields/StartTime__c.field-meta.xml
<CustomField>
    <fullName>StartTime__c</fullName>
    <description>Request Start Time</description>
    <label>Start Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

core/main/default/objects/CalloutTracker__e/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Http Request status</description>
    <label>Status</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

core/main/default/objects/CalloutTracker__e/fields/StatusCode__c.field-meta.xml
<CustomField>
    <fullName>StatusCode__c</fullName>
    <description>Http Request Status Code</description>
    <label>Status Code</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

core/main/default/objects/CalloutTracker__e/fields/Timeout__c.field-meta.xml
<CustomField>
    <fullName>Timeout__c</fullName>
    <description>Timeout value</description>
    <label>Timeout</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

core/main/default/objects/CalloutTracker__e/fields/TransactionId__c.field-meta.xml
<CustomField>
    <fullName>TransactionId__c</fullName>
    <description>Id to identify the transaction that has generated the event</description>
    <label>Transaction Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

core/main/default/objects/CalloutTracker__e/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <description>Id of the user that has made the request</description>
    <label>User Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

core/main/default/objects/CalloutTracker__e/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <description>username of the user that has made the request</description>
    <label>Username</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

core/main/default/classes/EM011_CalloutTracker_TEST.cls
/**
 * @author Sutharsan Pushparajah
 * @date 30/03/2021 - SSDL V1.3
 * @description Test class for EM011_CalloutTracker
 */
@isTest
private class EM011_CalloutTracker_TEST {
    
    /**
     * @author Sutharsan Pushparajah
     * @date 30/03/2021
     * @description Testing creating and publishing an event
     */
    @isTest
    public static void testCreate(){
        
        Database.SaveResult sr;

        WRP003_HttpRequest wrpReq = new WRP003_HttpRequest();
        wrpReq.endPoint = 'https://mock';
        wrpReq.requestType = 'GET';
        wrpReq.header.put('testH', 'testV');
        wrpReq.queryParameters = '/Id/xxxx';
        wrpReq.timeout = 120000;

        HttpResponse response = new HttpResponse();
        response.setStatus('OK');
        response.setStatusCode(200);

        Datetime theDate = System.now();
        
        Test.startTest();

        CalloutTracker__e calloutTrackerEvent = EM011_CalloutTracker.create('TID1', 'SID1', '/Account', theDate, theDate+1, 'sent', UserInfo.getUserId(), UserInfo.getUserName(), wrpReq);
        sr = EventBus.publish(calloutTrackerEvent);

        System.assertEquals(true, sr.isSuccess());
        System.assertEquals('TID1', calloutTrackerEvent.TransactionId__c);
        System.assertEquals('SID1', calloutTrackerEvent.ServiceId__c);
        System.assertEquals('/Account', calloutTrackerEvent.Resource__c);
        System.assertEquals(theDate, calloutTrackerEvent.StartTime__c);
        System.assertEquals(theDate+1, calloutTrackerEvent.EndTime__c);
        System.assertEquals('sent', calloutTrackerEvent.Message__c);
        System.assertEquals(UserInfo.getUserId(), calloutTrackerEvent.UserId__c);
        System.assertEquals(UserInfo.getUserName(), calloutTrackerEvent.Username__c);
        System.assertEquals(JSON.serialize(wrpReq.header),calloutTrackerEvent.Headers__c);
        System.assertEquals('GET', calloutTrackerEvent.HttpMethod__c);
        System.assertEquals('https://mock', calloutTrackerEvent.Endpoint__c);
        System.assertEquals('/Id/xxxx', calloutTrackerEvent.Queryparameters__c);
        System.assertEquals(120000, calloutTrackerEvent.Timeout__c);
        System.assertEquals(null, calloutTrackerEvent.Status__c);
        System.assertEquals(null, calloutTrackerEvent.StatusCode__c);

        wrpReq.httpResponse = response;
        calloutTrackerEvent = EM011_CalloutTracker.create('TID2', 'SID1', '/Account', theDate, theDate+1, 'sent', UserInfo.getUserId(), UserInfo.getUserName(), wrpReq);
        sr = EventBus.publish(calloutTrackerEvent);
        System.assertEquals(true, sr.isSuccess());
        System.assertEquals('TID2', calloutTrackerEvent.TransactionId__c);
        System.assertEquals('OK', calloutTrackerEvent.Status__c);
        System.assertEquals(200, calloutTrackerEvent.StatusCode__c);

        Test.stopTest();
    }
}