core/main/default/objects/CalloutTracker__e/CalloutTracker__e.object-meta.xml
<CustomObject>
    <description>Track callout activity</description>
    <label>Callout Tracker</label>
    <pluralLabel>Callouts Tracker</pluralLabel>
</CustomObject>

core/main/default/objects/CalloutTracker__e/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <description>Endpoint URL</description>
    <label>Endpoint</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

core/main/default/objects/CalloutTracker__e/fields/EndTime__c.field-meta.xml
<CustomField>
    <fullName>EndTime__c</fullName>
    <description>Request End Time</description>
    <label>End Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

core/main/default/objects/CalloutTracker__e/fields/Headers__c.field-meta.xml
<CustomField>
    <fullName>Headers__c</fullName>
    <description>Header of the request</description>
    <label>Headers</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

core/main/default/objects/CalloutTracker__e/fields/HttpMethod__c.field-meta.xml
<CustomField>
    <fullName>HttpMethod__c</fullName>
    <description>GET, POST, PUT, PATCH, DELETE</description>
    <label>Http Method</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

core/main/default/objects/CalloutTracker__e/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Extra message from the request and response</description>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

core/main/default/objects/CalloutTracker__e/fields/QueryParameters__c.field-meta.xml
<CustomField>
    <fullName>QueryParameters__c</fullName>
    <description>Parameters used in Query URL</description>
    <label>Query Parameters</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

core/main/default/objects/CalloutTracker__e/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <label>Request</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

core/main/default/objects/CalloutTracker__e/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <description>Name of the resource that was called</description>
    <label>Resource</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

core/main/default/objects/CalloutTracker__e/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <label>Response</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

core/main/default/objects/CalloutTracker__e/fields/ServiceId__c.field-meta.xml
<CustomField>
    <fullName>ServiceId__c</fullName>
    <description>Id of the service that was called</description>
    <label>Service Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

core/main/default/objects/CalloutTracker__e/fields/StartTime__c.field-meta.xml
<CustomField>
    <fullName>StartTime__c</fullName>
    <description>Request Start Time</description>
    <label>Start Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

core/main/default/objects/CalloutTracker__e/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Http Request status</description>
    <label>Status</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

core/main/default/objects/CalloutTracker__e/fields/StatusCode__c.field-meta.xml
<CustomField>
    <fullName>StatusCode__c</fullName>
    <description>Http Request Status Code</description>
    <label>Status Code</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

core/main/default/objects/CalloutTracker__e/fields/Timeout__c.field-meta.xml
<CustomField>
    <fullName>Timeout__c</fullName>
    <description>Timeout value</description>
    <label>Timeout</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

core/main/default/objects/CalloutTracker__e/fields/TransactionId__c.field-meta.xml
<CustomField>
    <fullName>TransactionId__c</fullName>
    <description>Id to identify the transaction that has generated the event</description>
    <label>Transaction Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

core/main/default/objects/CalloutTracker__e/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <description>Id of the user that has made the request</description>
    <label>User Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

core/main/default/objects/CalloutTracker__e/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <description>username of the user that has made the request</description>
    <label>Username</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

core/main/default/classes/EM011_CalloutTracker.cls
/**
 * @author Sutharsan Pushparajah
 * @date 29/03/2021 - SSDL V1.3
 * @description EM011_CalloutTracker - Entity to manage CalloutTracker__e platform event 
 */
public inherited sharing class EM011_CalloutTracker {
    
    /* Truncate field String if beyond */
    private static final Integer MAX_LENGTH_LONG_TEXT_AREA = 131000;
    private static final Integer MAX_LENGTH_TEXT_AREA = 31000;
    private static final Integer MAX_LENGTH_TEXT = 254; 

    /**
     * @author Sutharsan Pushparajah
     * @date 29/03/2021
     * @description Create an instance of CalloutTracker__e Event
     * @param transactionId Identify the id of the transaction
     * @param serviceId Identify the id of the service
     * @param resource Identify the name of the resource
     * @param startTime Identify the start time of the callout
     * @param endTime Identify the end time of the callout
     * @param message The callout message
     * @param userId Id of the connected user
     * @param userName userName of the connected user
     * @param wrpRequest extra information on the request
     * @return instance of CalloutTracker__e Event
     */
    public static CalloutTracker__e create(String transactionId, String serviceId, String resource, Datetime startTime, Datetime endTime, String message, String userId, String userName, WRP003_HttpRequest wrpRequest){
        String requestStr = '';
        String responseStr = '';

        CalloutTracker__e calloutTracker = new CalloutTracker__e();
        calloutTracker.TransactionId__c = transactionId;
        calloutTracker.ServiceId__c = serviceId;
        calloutTracker.Headers__c = truncate(JSON.serialize(wrpRequest.header), MAX_LENGTH_TEXT_AREA);
        calloutTracker.HttpMethod__c = wrpRequest.requestType;
        calloutTracker.Resource__c = truncate(resource, MAX_LENGTH_TEXT);
        calloutTracker.Endpoint__c = truncate(wrpRequest.endPoint, MAX_LENGTH_TEXT);
        calloutTracker.QueryParameters__c = truncate(wrpRequest.queryParameters, MAX_LENGTH_TEXT);
        calloutTracker.Timeout__c = wrpRequest.timeout;
        calloutTracker.StartTime__c = startTime;
        calloutTracker.EndTime__c = endTime;
        calloutTracker.UserId__c = userId;
        calloutTracker.Username__c = userName;
        calloutTracker.Message__c = truncate(message, MAX_LENGTH_TEXT_AREA);

        if (wrpRequest.httpResponse != null){
            calloutTracker.Status__c = truncate(wrpRequest.httpResponse.getStatus(), MAX_LENGTH_TEXT);
            calloutTracker.StatusCode__c = wrpRequest.httpResponse.getStatusCode();
        }

        if (String.isNotEmpty(wrpRequest.body)){
            requestStr = ' BODY['+wrpRequest.body+']';
        }

        if (wrpRequest.bodyDocument != null){
            requestStr += ' BODYDOC['+wrpRequest.bodyDocument.toXmlString()+']';
        }

        if (wrpRequest.httpResponse != null){
            responseStr = 'BODY['+wrpRequest.httpResponse.getBody()+']';
        }

        if (wrpRequest.soapRequest == null){
            calloutTracker.Request__c = truncate(requestStr, MAX_LENGTH_LONG_TEXT_AREA);
            calloutTracker.Response__c = truncate(responseStr, MAX_LENGTH_LONG_TEXT_AREA);
        } else {
            calloutTracker.Request__c = truncate(wrpRequest.soapRequest+requestStr, MAX_LENGTH_LONG_TEXT_AREA);
            calloutTracker.Response__c = truncate(wrpRequest.soapResponse+responseStr, MAX_LENGTH_LONG_TEXT_AREA);
        }

        return calloutTracker;
    }

    /* @author Sutharsan Pushparajah
     * @date 22/09/2021
     * @description truncate and return the string representation of the object 
     * @param value object to transform/truncate into string
     * @param maxLength maximum length allowed
     * @return substring to respect max length
     */
    @testVisible
    private static String truncate(Object value, Integer maxLength){
        String temp = null;

        if (value != null){
            temp = String.valueOf(value);
            
            if (temp.length() > maxLength){
                temp = temp.substring(0, maxLength);
            }

            temp = temp.replaceAll('\\$', '&#x24;');
        }

        return temp;
    }
}