core/main/default/objects/CoreSetting__mdt/CoreSetting__mdt.object-meta.xml
<CustomObject>
    <description>SSDL Framework core settings</description>
    <label>Core Setting</label>
    <pluralLabel>Core Settings</pluralLabel>
</CustomObject>

core/main/default/objects/CoreSetting__mdt/fields/BypassAllTriggerPermission__c.field-meta.xml
<CustomField>
    <fullName>BypassAllTriggerPermission__c</fullName>
    <description>Custom Permission Name used to Bypass all triggers</description>
    <label>Bypass All Trigger Permission</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

core/main/default/objects/CoreSetting__mdt/fields/BypassSchemaDescriberPermission__c.field-meta.xml
<CustomField>
    <fullName>BypassSchemaDescriberPermission__c</fullName>
    <description>Custom Permission Name used to Bypass schema describer check</description>
    <label>Bypass Schema Describer Permission</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

core/main/default/objects/CoreSetting__mdt/fields/BypassStripinaccessiblePermission__c.field-meta.xml
<CustomField>
    <fullName>BypassStripinaccessiblePermission__c</fullName>
    <description>Custom Permission Name used to Bypass StripInaccessible</description>
    <label>Bypass Stripinaccessible Permission</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

core/main/default/objects/CoreSetting__mdt/fields/BypassWithSecurityPermission__c.field-meta.xml
<CustomField>
    <fullName>BypassWithSecurityPermission__c</fullName>
    <description>Custom Permission Name used to Bypass with security enforced</description>
    <label>Bypass With Security Permission</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

core/main/default/objects/CoreSetting__mdt/fields/CalloutTrackingEnabled__c.field-meta.xml
<CustomField>
    <fullName>CalloutTrackingEnabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Monitor callout activities and send a platform event</description>
    <inlineHelpText>Monitor callout activities and send a platform event</inlineHelpText>
    <label>Callout Tracking Enabled</label>
    <type>Checkbox</type>
</CustomField>

core/main/default/objects/CoreSetting__mdt/fields/CoreTriggerManagerClass__c.field-meta.xml
<CustomField>
    <fullName>CoreTriggerManagerClass__c</fullName>
    <description>Trigger Manager Core Class Name used to instanciate dynamically default one or project specific one</description>
    <inlineHelpText>prefix your class name with &quot;local.&quot; if not using default one.</inlineHelpText>
    <label>Core Trigger Manager Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

core/main/default/objects/CoreSetting__mdt/fields/EnableCalloutTrackingPermission__c.field-meta.xml
<CustomField>
    <fullName>EnableCalloutTrackingPermission__c</fullName>
    <description>Track callout and generate an event per user</description>
    <inlineHelpText>Track callout and generate an event per user</inlineHelpText>
    <label>Enable Callout Tracking Permission</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

core/main/default/objects/CoreSetting__mdt/fields/EnableLoggingEventPermission__c.field-meta.xml
<CustomField>
    <fullName>EnableLoggingEventPermission__c</fullName>
    <description>Generate and send platform event per user</description>
    <inlineHelpText>Generate and send platform event per user</inlineHelpText>
    <label>Enable Logging Event Permission</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

core/main/default/objects/CoreSetting__mdt/fields/EnableLoggingPermission__c.field-meta.xml
<CustomField>
    <fullName>EnableLoggingPermission__c</fullName>
    <description>Custom Permission to enable logging per user</description>
    <inlineHelpText>Custom Permission to enable logging per user</inlineHelpText>
    <label>Enable Logging Permission</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

core/main/default/objects/CoreSetting__mdt/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Core Setting used when checked for the corresponding org</description>
    <label>is Active ?</label>
    <type>Checkbox</type>
</CustomField>

core/main/default/objects/CoreSetting__mdt/fields/IsDefault__c.field-meta.xml
<CustomField>
    <fullName>IsDefault__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Default setting when configuration has not been set for org</description>
    <label>is Default ?</label>
    <type>Checkbox</type>
</CustomField>

core/main/default/objects/CoreSetting__mdt/fields/LoggingEnabled__c.field-meta.xml
<CustomField>
    <fullName>LoggingEnabled__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Activate or desactivate custom debug from APU000_Logger</description>
    <label>Logging Enabled</label>
    <type>Checkbox</type>
</CustomField>

core/main/default/objects/CoreSetting__mdt/fields/LoggingEventEnabled__c.field-meta.xml
<CustomField>
    <fullName>LoggingEventEnabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Generate and send a platform event</description>
    <inlineHelpText>Generate and send a platform event</inlineHelpText>
    <label>Logging Event Enabled</label>
    <type>Checkbox</type>
</CustomField>

core/main/default/objects/CoreSetting__mdt/fields/OrgId__c.field-meta.xml
<CustomField>
    <fullName>OrgId__c</fullName>
    <description>Id of the org where setting is available</description>
    <label>Org Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

core/main/default/objects/CoreSetting__mdt/fields/RecursionLevel__c.field-meta.xml
<CustomField>
    <fullName>RecursionLevel__c</fullName>
    <description>Set trigger recursion level from 0-9, null means no restriction</description>
    <inlineHelpText>Set trigger recursion level from 0-9, null means no restriction</inlineHelpText>
    <label>Recursion Level</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

core/main/default/objects/CoreSetting__mdt/fields/SobjectInfoSessionCache__c.field-meta.xml
<CustomField>
    <fullName>SobjectInfoSessionCache__c</fullName>
    <description>Session cache partition used to store user and Sobject information</description>
    <label>SObject Info Session Cache</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

core/main/default/objects/CoreSetting__mdt/fields/UserInfoSessionCache__c.field-meta.xml
<CustomField>
    <fullName>UserInfoSessionCache__c</fullName>
    <description>Session Partition used to cahce user info</description>
    <label>User Info Session Cache</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

core/main/default/objects/CoreSetting__mdt/fields/WithSchemaDescriber__c.field-meta.xml
<CustomField>
    <fullName>WithSchemaDescriber__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Enforce field and object level data protection with Schema Describer</description>
    <inlineHelpText>Enforce field and object level data protection with Schema Describer</inlineHelpText>
    <label>With Schema Describer</label>
    <type>Checkbox</type>
</CustomField>

core/main/default/objects/CoreSetting__mdt/fields/WithSecurityEnforced__c.field-meta.xml
<CustomField>
    <fullName>WithSecurityEnforced__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Add WITH SECURITY_ENFORCED to SOQL queries</description>
    <label>With Security Enforced</label>
    <type>Checkbox</type>
</CustomField>

core/main/default/objects/CoreSetting__mdt/fields/WithStripInaccessible__c.field-meta.xml
<CustomField>
    <fullName>WithStripInaccessible__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Enforce field and object level data protection</description>
    <inlineHelpText>Enforce field and object level data protection</inlineHelpText>
    <label>With StripInaccessible</label>
    <type>Checkbox</type>
</CustomField>

core/main/default/classes/APC000_CoreSetting.cls
/**
 * @author Sutharsan Pushparajah
 * @date 27/08/2019 - SSDL V1.0
 * @date 17/02/2021 - Adding StripInaccessible feature
 * @date 26/03/2021 - Mock Core Setting
 * @description APC000_CoreSetting - Core Setting Custom Metadata Type to retrieve framework settings
 */
public inherited sharing class APC000_CoreSetting{
    
    /* mock core setting : do not change values as it used in Test class */
    private static final String MOCK_CORE_SETTING = 'MockCoreSettings';
    /* default core setting for the framework */
    public static CoreSetting__mdt coreSetting;

    static {
        CoreSetting__mdt mockCoreSetting;
        String orgId = UserInfo.getOrganizationId();
        
        List<CoreSetting__mdt> coreSettingList = new List<CoreSetting__mdt>([select BypassAllTriggerPermission__c, DeveloperName,
                                                    CoreTriggerManagerClass__c, IsActive__c, IsDefault__c, 
                                                    OrgId__c, RecursionLevel__c,
                                                    SobjectInfoSessionCache__c, UserInfoSessionCache__c,
                                                    WithSecurityEnforced__c, WithStripInaccessible__c, WithSchemaDescriber__c,
                                                    BypassSchemaDescriberPermission__c, BypassStripinaccessiblePermission__c, BypassWithSecurityPermission__c,
                                                    LoggingEnabled__c, EnableLoggingPermission__c, LoggingEventEnabled__c, EnableLoggingEventPermission__c, 
                                                    CalloutTrackingEnabled__c, EnableCalloutTrackingPermission__c
                                                    from CoreSetting__mdt 
                                                    where IsActive__c = true WITH SYSTEM_MODE]);

        for (CoreSetting__mdt cs : coreSettingList){
            if (cs.DeveloperName == MOCK_CORE_SETTING){
                mockCoreSetting = cs;
            }

            if (cs.IsActive__c){
                if (orgId == cs.orgId__c){
                    coreSetting = cs;
                    break;
                } else if (cs.IsDefault__c){
                    //Keep the default one if setting is not found for current org 
                    coreSetting = cs;
                }
            }
        }

        //To validate test unit, we replace the core setting with the one used in test context and ensure that previous lines are covered
        if (Test.isRunningTest()){
            coreSetting = mockCoreSetting;
        }
    }
}