core/main/default/objects/CalloutTrackerExt__c/CalloutTrackerExt__c.object-meta.xml
<CustomObject>
    <description>Custom Object to store captured event</description>
    <label>Callout Tracker Ext</label>
    <nameField>
        <label>Callout Tracker Ext	 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Callouts Tracker Ext</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

core/main/default/objects/CalloutTrackerExt__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <description>Endpoint URL</description>
    <label>Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

core/main/default/objects/CalloutTrackerExt__c/fields/EndTime__c.field-meta.xml
<CustomField>
    <fullName>EndTime__c</fullName>
    <description>Request End Time</description>
    <label>End Time</label>
    <type>DateTime</type>
</CustomField>

core/main/default/objects/CalloutTrackerExt__c/fields/Headers__c.field-meta.xml
<CustomField>
    <fullName>Headers__c</fullName>
    <description>Header of the request</description>
    <label>Headers</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

core/main/default/objects/CalloutTrackerExt__c/fields/HttpMethod__c.field-meta.xml
<CustomField>
    <fullName>HttpMethod__c</fullName>
    <description>GET, POST, PUT, PATCH, DELETE</description>
    <label>Http Method</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

core/main/default/objects/CalloutTrackerExt__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Extra message from the request and response</description>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

core/main/default/objects/CalloutTrackerExt__c/fields/QueryParameters__c.field-meta.xml
<CustomField>
    <fullName>QueryParameters__c</fullName>
    <description>Parameters used in Query URL</description>
    <label>Query Parameters</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

core/main/default/objects/CalloutTrackerExt__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <description>Http Request</description>
    <label>Request</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

core/main/default/objects/CalloutTrackerExt__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <description>Name of the resource that was called</description>
    <label>Resource</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

core/main/default/objects/CalloutTrackerExt__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <description>Http Response</description>
    <label>Response</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

core/main/default/objects/CalloutTrackerExt__c/fields/ServiceId__c.field-meta.xml
<CustomField>
    <fullName>ServiceId__c</fullName>
    <description>Id of the service that was called</description>
    <label>Service Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

core/main/default/objects/CalloutTrackerExt__c/fields/StartTime__c.field-meta.xml
<CustomField>
    <fullName>StartTime__c</fullName>
    <description>Request Start Time</description>
    <label>Start Time</label>
    <type>DateTime</type>
</CustomField>

core/main/default/objects/CalloutTrackerExt__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Http Request status</description>
    <label>Status</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

core/main/default/objects/CalloutTrackerExt__c/fields/StatusCode__c.field-meta.xml
<CustomField>
    <fullName>StatusCode__c</fullName>
    <description>Http Request Status Code</description>
    <label>Status Code</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

core/main/default/objects/CalloutTrackerExt__c/fields/Timeout__c.field-meta.xml
<CustomField>
    <fullName>Timeout__c</fullName>
    <description>Timeout value</description>
    <label>Timeout</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

core/main/default/objects/CalloutTrackerExt__c/fields/TransactionId__c.field-meta.xml
<CustomField>
    <fullName>TransactionId__c</fullName>
    <description>Id to identify the transaction that has generated the event</description>
    <label>Transaction Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

core/main/default/objects/CalloutTrackerExt__c/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <description>Id of the user that has made the request</description>
    <label>User Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

core/main/default/objects/CalloutTrackerExt__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <description>username of the user that has made the request</description>
    <label>Username</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

core/main/default/classes/EM013_CalloutTrackerExt.cls
/**
 * @author Sutharsan Pushparajah
 * @date 05/10/2021 - SSDL V1.4
 * @description EM013_CalloutTrackerExt - Entity to manage CalloutTrackerExt__c 
 */
public inherited sharing class EM013_CalloutTrackerExt {
    public static ITF001_DataManager datamanager = new DM001_SObjectInstance(SObjectType.CalloutTrackerExt__c.Name, 'EM013_CalloutTrackerExt');

    /**
     * @author Sutharsan Pushparajah
     * @date 06/10/2021
     * @description Retrieve a list of all CalloutTrackerExt__c records to use in test context only
     * @return List<CalloutTrackerExt__c> Lif of all CalloutTrackerExt__c records
     */
    public static List<CalloutTrackerExt__c> getList(){
        WRP002_QueryBuilder wrpQuery = new WRP002_QueryBuilder('Id, CreatedDate, Name, EndTime__c, Endpoint__c, Headers__c, HttpMethod__c, Message__c, QueryParameters__c, Request__c, Resource__c, Response__c, ServiceId__c, StartTime__c, Status__c, StatusCode__c,  Timeout__c, TransactionId__c, UserId__c, Username__c', null, null);
        wrpQuery = datamanager.query(wrpQuery);

        return wrpQuery.results;
    }
}