core/main/default/objects/CalloutTrackerExt__c/CalloutTrackerExt__c.object-meta.xml
<CustomObject>
    <description>Custom Object to store captured event</description>
    <label>Callout Tracker Ext</label>
    <nameField>
        <label>Callout Tracker Ext	 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Callouts Tracker Ext</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

core/main/default/objects/CalloutTrackerExt__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <description>Endpoint URL</description>
    <label>Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

core/main/default/objects/CalloutTrackerExt__c/fields/EndTime__c.field-meta.xml
<CustomField>
    <fullName>EndTime__c</fullName>
    <description>Request End Time</description>
    <label>End Time</label>
    <type>DateTime</type>
</CustomField>

core/main/default/objects/CalloutTrackerExt__c/fields/HttpMethod__c.field-meta.xml
<CustomField>
    <fullName>HttpMethod__c</fullName>
    <description>GET, POST, PUT, PATCH, DELETE</description>
    <label>Http Method</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

core/main/default/objects/CalloutTrackerExt__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Extra message from the request and response</description>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

core/main/default/objects/CalloutTrackerExt__c/fields/QueryParameters__c.field-meta.xml
<CustomField>
    <fullName>QueryParameters__c</fullName>
    <description>Parameters used in Query URL</description>
    <label>Query Parameters</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

core/main/default/objects/CalloutTrackerExt__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <description>Http Request</description>
    <label>Request</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

core/main/default/objects/CalloutTrackerExt__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <description>Name of the resource that was called</description>
    <label>Resource</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

core/main/default/objects/CalloutTrackerExt__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <description>Http Response</description>
    <label>Response</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

core/main/default/objects/CalloutTrackerExt__c/fields/ServiceId__c.field-meta.xml
<CustomField>
    <fullName>ServiceId__c</fullName>
    <description>Id of the service that was called</description>
    <label>Service Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

core/main/default/objects/CalloutTrackerExt__c/fields/StartTime__c.field-meta.xml
<CustomField>
    <fullName>StartTime__c</fullName>
    <description>Request Start Time</description>
    <label>Start Time</label>
    <type>DateTime</type>
</CustomField>

core/main/default/objects/CalloutTrackerExt__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Http Request status</description>
    <label>Status</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

core/main/default/objects/CalloutTrackerExt__c/fields/StatusCode__c.field-meta.xml
<CustomField>
    <fullName>StatusCode__c</fullName>
    <description>Http Request Status Code</description>
    <label>Status Code</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

core/main/default/objects/CalloutTrackerExt__c/fields/Timeout__c.field-meta.xml
<CustomField>
    <fullName>Timeout__c</fullName>
    <description>Timeout value</description>
    <label>Timeout</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

core/main/default/objects/CalloutTrackerExt__c/fields/TransactionId__c.field-meta.xml
<CustomField>
    <fullName>TransactionId__c</fullName>
    <description>Id to identify the transaction that has generated the event</description>
    <label>Transaction Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

core/main/default/objects/CalloutTrackerExt__c/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <description>Id of the user that has made the request</description>
    <label>User Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

core/main/default/objects/CalloutTrackerExt__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <description>username of the user that has made the request</description>
    <label>Username</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

core/main/default/classes/EM013_CalloutTrackerExt_TEST.cls
/**
 * @author Sutharsan Pushparajah
 * @date 05/10/2021 - SSDL V1.4
 * @description Test class for EM013_CalloutTrackerExt_TEST
 */
@isTest
private class EM013_CalloutTrackerExt_TEST {

    @TestSetup
    private static void initData(){
        TST000_TestDataFactory.createStandardUserForFramework();
    }
  
    /**
     * @author Sutharsan Pushparajah
     * @date 05/10/2021
     * @description Testing callout tracking results for IP
     */
    @isTest
    private static void testTrackCalloutIP(){
        
        String transactionId;
        
        Test.startTest();

        //New behavior SPRING23: Static variables are reset when called in multi user / flow context, do not persist anymore globally into whole transaction
        transactionId = APU002_Context.TRANSACTION_GUID;
        
        System.runAs(TST000_TestDataFactory.getStandardUserForFramework()){
            APU002_Context.bypassEventPublishingInTestContext = false;

            Boolean result = APU000_Logger.trackCallout(null, null, null);
            System.assertEquals(false, result);


            Map<String, Object> input = new Map<String, Object>{APU000_Logger.SERVICE_NAME => 'TestingMockService', 
                                                                APU000_Logger.METHOD => 'POST',
                                                                APU000_Logger.MESSAGE => 'test',
                                                                APU000_Logger.STATUS => 'OK',
                                                                APU000_Logger.STATUS_CODE => 200,
                                                                APU000_Logger.REQUEST => 'Request',
                                                                APU000_Logger.RESPONSE => 'Response',
                                                                APU000_Logger.QUERY_PARAMETERS => '?q=1'};
            result = APU000_Logger.trackCallout(input, null, null);
            System.assertEquals(true, result);

            //FIRE SOME EVENTS
            Test.stopTest();

            List<CalloutTrackerExt__c> resultList = EM013_CalloutTrackerExt.getList();

            System.assertNotEquals(null, resultList);
            System.assertEquals(1, resultList.size());

            CalloutTrackerExt__c ctext = resultList.get(0);
            System.assertNotEquals(null, ctext.EndTime__c);
            System.assertEquals('CALLOUT:MOCK2/mock', ctext.Endpoint__c);
            System.assertEquals('POST', ctext.HttpMethod__c);
            System.assertEquals('test', ctext.Message__c);
            System.assertEquals('?q=1', ctext.QueryParameters__c);
            System.assertEquals('BODY[Request]', ctext.Request__c);
            System.assertEquals('/mock', ctext.Resource__c);
            System.assertEquals('BODY[Response]', ctext.Response__c);
            System.assertEquals('SID-0000', ctext.ServiceId__c);
            System.assertNotEquals(null, ctext.StartTime__c);
            System.assertEquals('OK', ctext.Status__c); 
            System.assertEquals(200, ctext.StatusCode__c);
            System.assertEquals(120000, ctext.Timeout__c);
            System.assertEquals(transactionId, ctext.TransactionId__c);
            System.assertEquals(UserInfo.getUserId(), ctext.UserId__c);
            System.assertEquals(UserInfo.getUserName(), ctext.Username__c);

            APU002_Context.bypassEventPublishingInTestContext = true;
        }
    }
}