core/main/default/objects/LoggingMessage__e/LoggingMessage__e.object-meta.xml
<CustomObject>
    <description>Capture Logging Events when enabled</description>
    <label>Logging Message</label>
    <pluralLabel>Logging Messages</pluralLabel>
</CustomObject>

core/main/default/objects/LoggingMessage__e/fields/ClassName__c.field-meta.xml
<CustomField>
    <fullName>ClassName__c</fullName>
    <description>Name of the class that publish the event</description>
    <label>Class Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

core/main/default/objects/LoggingMessage__e/fields/EndTime__c.field-meta.xml
<CustomField>
    <fullName>EndTime__c</fullName>
    <description>End Time of the logging</description>
    <label>End Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

core/main/default/objects/LoggingMessage__e/fields/LogLevel__c.field-meta.xml
<CustomField>
    <fullName>LogLevel__c</fullName>
    <description>Log Level of the message</description>
    <label>Log Level</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

core/main/default/objects/LoggingMessage__e/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Logging message</description>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

core/main/default/objects/LoggingMessage__e/fields/MethodName__c.field-meta.xml
<CustomField>
    <fullName>MethodName__c</fullName>
    <description>Name of the method that publish the event</description>
    <label>Method Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

core/main/default/objects/LoggingMessage__e/fields/StartTime__c.field-meta.xml
<CustomField>
    <fullName>StartTime__c</fullName>
    <description>Start time of the logging</description>
    <label>Start Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

core/main/default/objects/LoggingMessage__e/fields/TransactionId__c.field-meta.xml
<CustomField>
    <fullName>TransactionId__c</fullName>
    <description>Identify the transaction that publish this event</description>
    <label>Transaction Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

core/main/default/objects/LoggingMessage__e/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <description>Id of the user that has fired this event</description>
    <label>User Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

core/main/default/objects/LoggingMessage__e/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <description>Username of the user that has fired this event</description>
    <label>Username</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

core/main/default/classes/EM010_LoggingMessage.cls
/**
 * @author Sutharsan Pushparajah
 * @date 29/03/2021 - SSDL V1.3
 * @description EM010_LoggingMessage - Entity to manage LogginMessage__e platform event 
 */
public inherited sharing class EM010_LoggingMessage {

    /**
     * @author Sutharsan Pushparajah
     * @date 29/03/2021
     * @description Create an instance of LoggingMessage__e Event
     * @param transactionId Identify the id of the transaction
     * @param className Idnetify the caller class
     * @param methodName Identify the caller method
     * @param logLevel Identify the Log level 
     * @param startTime Identify the start time of the log
     * @param endTime Identify the end time of the log
     * @param message The logging message
     * @param userId Id of the connected user
     * @param userName userName of the connected user
     * @return instance of LoggingMessage__e Event
     */
    public static LoggingMessage__e create(String transactionId, String className, string methodName, String logLevel, 
    Datetime startTime, Datetime endTime, String message, String userId, String userName) {
        LoggingMessage__e messageEvent = new LoggingMessage__e();
        messageEvent.TransactionId__c = transactionId;
        messageEvent.ClassName__c = className;
        messageEvent.MethodName__c = methodName;
        messageEvent.Loglevel__c = logLevel;
        messageEvent.StartTime__c = startTime;
        messageEvent.EndTime__c = endTime;
        messageEvent.Message__c = message;
        messageEvent.UserId__c = userId;
        messageEvent.userName__c = userName;

        return messageEvent;
    }
}