core/main/default/objects/LoggingMessage__e/LoggingMessage__e.object-meta.xml
<CustomObject>
    <description>Capture Logging Events when enabled</description>
    <label>Logging Message</label>
    <pluralLabel>Logging Messages</pluralLabel>
</CustomObject>

core/main/default/objects/LoggingMessage__e/fields/ClassName__c.field-meta.xml
<CustomField>
    <fullName>ClassName__c</fullName>
    <description>Name of the class that publish the event</description>
    <label>Class Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

core/main/default/objects/LoggingMessage__e/fields/EndTime__c.field-meta.xml
<CustomField>
    <fullName>EndTime__c</fullName>
    <description>End Time of the logging</description>
    <label>End Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

core/main/default/objects/LoggingMessage__e/fields/LogLevel__c.field-meta.xml
<CustomField>
    <fullName>LogLevel__c</fullName>
    <description>Log Level of the message</description>
    <label>Log Level</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

core/main/default/objects/LoggingMessage__e/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Logging message</description>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

core/main/default/objects/LoggingMessage__e/fields/MethodName__c.field-meta.xml
<CustomField>
    <fullName>MethodName__c</fullName>
    <description>Name of the method that publish the event</description>
    <label>Method Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

core/main/default/objects/LoggingMessage__e/fields/StartTime__c.field-meta.xml
<CustomField>
    <fullName>StartTime__c</fullName>
    <description>Start time of the logging</description>
    <label>Start Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

core/main/default/objects/LoggingMessage__e/fields/TransactionId__c.field-meta.xml
<CustomField>
    <fullName>TransactionId__c</fullName>
    <description>Identify the transaction that publish this event</description>
    <label>Transaction Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

core/main/default/objects/LoggingMessage__e/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <description>Id of the user that has fired this event</description>
    <label>User Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

core/main/default/objects/LoggingMessage__e/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <description>Username of the user that has fired this event</description>
    <label>Username</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

core/main/default/classes/EM010_LoggingMessage_TEST.cls
/**
 * @author Sutharsan Pushparajah
 * @date 29/03/2021 - SSDL V1.3
 * @description Test class for EM010_LoggingMessage
 */
@isTest
private class EM010_LoggingMessage_TEST {
    
    /**
     * @author Sutharsan Pushparajah
     * @date 29/03/2021
     * @description Testing creating and publishing an event
     */
    @isTest
    public static void testCreate(){
        
        Database.SaveResult sr;
        
        Test.startTest();

        Datetime theTime = System.now();
        LoggingMessage__e messageEvent = EM010_LoggingMessage.create('testId', 'testClass', 'testMethod', 'INFO', theTime, theTime+1, 'Testing', UserInfo.getUserId(), UserInfo.getUserName());
        sr = EventBus.publish(messageEvent);
        System.assertEquals('testId', messageEvent.TransactionId__c);
        System.assertEquals('testClass', messageEvent.ClassName__c);
        System.assertEquals('testMethod', messageEvent.MethodName__c);
        System.assertEquals('INFO', messageEvent.LogLevel__c);
        System.assertEquals(theTime, messageEvent.StartTime__c);
        System.assertEquals(theTime+1, messageEvent.EndTime__c);
        System.assertEquals('Testing', messageEvent.Message__c);
        System.assertEquals(UserInfo.getUserId(), messageEvent.UserId__c);
        System.assertEquals(UserInfo.getUserName(), messageEvent.UserName__c);
        System.assertEquals(true, sr.isSuccess());

        Test.stopTest();
    }
}